In [54]:
import struct 
import numpy as np
from sklearn import neighbors, metrics
import matplotlib.pyplot as plt
%matplotlib inline

In [55]:
def read_idx(file_name):
    with open(file_name, 'rb') as f:
        zero, data_type, dims = struct.unpack('>HBB', f.read(4))
        shape = tuple(struct.unpack('>I', f.read(4))[0] for d in range(dims))
        return np.fromstring(f.read(), dtype = np.uint8).reshape(shape)

In [56]:
from PIL import Image
import numpy as np
def check_data(img, label):
    img = Image.fromarray(img)
    img.show()
    print(label)

In [57]:
def flat_matrix(matrix, rows_num, col_num):
    return np.reshape(matrix, (rows_num, col_num))

In [58]:
train_data = flat_matrix(read_idx('train-images.idx3-ubyte'), 60000, 28*28)
train_label = read_idx('train-labels.idx1-ubyte')
test_data = flat_matrix(read_idx('t10k-images.idx3-ubyte'), 10000, 28*28)
test_label = read_idx('t10k-labels.idx1-ubyte')

C:\Users\shilo\AppData\Local\Temp\ipykernel_8536\132011618.py:5: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(f.read(), dtype = np.uint8).reshape(shape)


In [59]:
#train_mask = ((train_label == 2) | (train_label == 3) | (train_label == 8))
X = train_data
Y = train_label
print(X)
print(Y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[5 0 4 ... 5 6 8]


In [60]:
#test_mask = ((test_label == 2) | (test_label == 3) | (test_label == 8))
x_test = test_data
y_true = test_label
print(x_test)
print(y_true)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[7 2 1 ... 4 5 6]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
res = 0
res_k = 0
y_pred_res = y_true
for k in range(1,20):
    knn = KNeighborsClassifier(n_neighbors=k).fit(X, Y)
    y_pred = knn.predict(x_test)
    conf_matrix = confusion_matrix(y_true, y_pred)
    tesmp_res = sum(conf_matrix[i][i] for i in range(len(conf_matrix)))
    if tesmp_res > res:
        res = tesmp_res
        res_k = k
        y_pred_res = y_pred


In [ ]:
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import classification_report
print(res_k)
knn = KNeighborsClassifier(n_neighbors=res_k).fit(X, Y)
plot_confusion_matrix(knn, x_test, y_true) 
plt.show()
print(classification_report(y_true, y_pred_res, labels=[i for i in range(10)]))